version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: voice_expense_tracker_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-voice_expense_tracker}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - voice_expense_tracker_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  voice_expense_tracker_data:
    name: voice_expense_tracker_data
